import Navbar from '@/components/shared/Navbar';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.scss';
import Footer from '@/components/shared/Footer';

const mainFont = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'X-Sports',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
