import Navbar from '@/components/shared/Navbar';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.scss';
import { AuthProvider } from '@/context/Web3AuthContext';

const mainFont = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
